FROM aarch64/node:7.6
COPY qemu-aarch64-static /usr/bin/qemu-aarch64-static

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install

# Bundle app source
COPY . /usr/src/app

CMD [ "npm", "start" ]
